## MTP  - by Ayush

In [127]:
import numpy as np

In [128]:
vertical_grids = int(input("enter the no. of vertical grids = "))
horizontal_grids = int(input("enter the no. of horizontal grids = "))


enter the no. of vertical grids = 50
enter the no. of horizontal grids = 50


In [129]:
gene_size = (vertical_grids,horizontal_grids)

In [130]:
# def gene_set:
#     A = np.random.randint(0,2,size=(50,50))
# gene_size = gene_set.shape
# row_size=gene_size[0] ; column_size=gene_size[1]


In [131]:
def generate_parent(gene_size):                       #add gene_set
    genes = np.random.randint(0,2,size=gene_size)
    return genes

In [132]:
def get_fitness(genes):
    return np.sum(genes)

In [133]:
p1 = generate_parent(gene_size)
p2 = generate_parent(gene_size)

In [134]:
def mutate(parent):       #change parent/genes
    
    i = np.random.randint(0,vertical_grids)
    j = np.random.randint(0,horizontal_grids)
    
    parent[i,j] = 1-parent[i,j]
    print("mutated element index:",i+1,j+1)
    
    return parent
    

In [135]:
print(p1)

[[1 1 0 ... 0 1 1]
 [0 0 1 ... 1 0 0]
 [1 0 1 ... 0 1 0]
 ...
 [0 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 1]
 [0 1 1 ... 1 0 0]]


In [136]:
A = mutate(p1)
print(A)

mutated element index: 37 6
[[1 1 0 ... 0 1 1]
 [0 0 1 ... 1 0 0]
 [1 0 1 ... 0 1 0]
 ...
 [0 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 1]
 [0 1 1 ... 1 0 0]]


---

In [137]:
print(get_fitness(p1))

1193
